---
- hosts: all
  vars:
      HOME_PATH: "{{ ansible_env.HOME }}"
      BIN_PATH: "{{ ansible_env.HOME }}/local/.bin"
      ANTIGEN_PATH: "{{ ansible_env.HOME }}/antigen"
      BASH_IT_PATH: "{{ ansible_env.HOME }}/.bash_it"
      GIT_NUMBER_PATH: "{{ ansible_env.HOME }}/git-number"
      SPACEMACS_PATH: "{{ ansible_env.HOME }}/.emacs.d"
      TPM_PATH: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

  roles:
      - role: geerlingguy.git
        git_packagese:
            - git
        become: true
      - role: howtodojo.tmux
        become: true
      - role: theNewFlesh.tree
        become: true
      - role: ngpestelos.fasd
        become: true

  tasks:
      - name: Create user bin directory
        file:
            path: "{{ BIN_PATH }}"
            state: directory

      - name: Install antigen
        git:
            repo: https://github.com/zsh-users/antigen
            dest: "{{ ANTIGEN_PATH }}"

      - name: Install bash-it
        git:
            repo: https://github.com/Bash-it/bash-it
            dest: "{{ BASH_IT_PATH }}"

      - name: Clone spacemacs
        git:
            repo: https://github.com/syl20bnr/spacemacs
            dest: "{{ SPACEMACS_PATH }}"

      - name: Symlink dotfiles
        file:
            src: "{{ playbook_dir }}/../{{ item.path }}"
            dest: "{{ HOME_PATH }}/{{ item.name }}"
            state: link
            force: yes
        with_items:
            - {path: "shells/.bashrc", name: ".bashrc"}
            - {path: "shells/.zshrc", name: ".zshrc"}
            - {path: "shells/.aliases", name: ".aliases"}
            - {path: "git/.gitconfig", name: ".gitconfig"}
            - {path: "git/.gitignore_global", name: ".gitignore_global"}
            - {path: "other/.tmux.conf", name: ".tmux.conf"}
            - {path: "other/.fasdrc", name: ".fasdrc"}
            - {path: "other/.ctags", name: ".ctags"}
            - {path: "editors/vim/.vimrc", name: ".vimrc"}
            - {path: "editors/vim/.vim", name: ".vim"}
            - {path: "editors/emacs/.spacemacs", name: ".emacs.d/.spacemacs"}
            - {path: "editors/emacs/snippets", name: ".emacs.d/snippets"}
            - {path: "file_managers/vifm/vifmrc", name: ".vifm/vifmrc"}
            - {path: "other/gpg.conf", name: ".gnupg/gpg.conf"}

      - name: Check if vim plugins are installed
        stat:
            path: "{{ playbook_dir }}/../editors/vim/.vim/bundle/vim-pathogen/.git"
        register: vim_plugins

      - name: Install vim plugins
        command: git submodule update --init
        args:
            chdir: "{{ playbook_dir }}/.."
        when: vim_plugins.stat.isdir is defined and vim_plugins.stat.isdir

      - name: Clone git-number
        git:
           repo: https://github.com/holygeek/git-number
           dest: "{{ GIT_NUMBER_PATH }}"

      - name: Symlink git-number files
        file:
           src: "{{ GIT_NUMBER_PATH }}/{{ item.name }}"
           dest: "{{ BIN_PATH }}/{{ item.name }}"
           state: link
           force: yes
        with_items:
           - {name: "git-number"}
           - {name: "git-list"}
           - {name: "git-id"}

      - name: Install emacs
        package: name=emacs state=present
        become: true

      - name: Clone tmux-plugin-manager
        git:
            repo: https://github.com/tmux-plugins/tpm
            dest: "{{ TPM_PATH }}"

      - name: Install httpie
        package: name=httpie state=present
        become: true

